# Generated by Django 4.1.3 on 2022-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chefs/'),
        ),
    ]
